export const FETCH_POKEDEX_SUCCESS = 'FETCH_POKEDEX_SUCCESS';
export const SET_STATUS = 'SET_STATUS';
export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS'
export const POKEMON_UPDATE = 'POKEMON_UPDATE';
export const FILTER_POKEMON = 'FILTER_POKEMON';
export const FETCH_DESCRIPTION_SUCCESS= 'FETCH_DESCRIPTION_SUCCESS';
